#!/bin/python3

import os
import sys


#
# Complete the simpleArraySum function below.
#
def simpleArraySum(ar):
    sum = 0
    for i in ar:
         sum += i
    return sum

        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = simpleArraySum(ar)
      
    fptr.write(str(result) + '\n')

    fptr.close()

    
    #Test Case 1
    #array of [10,32,44,55,66,77]
    
    #Test Case 2
    #array of [12,134,145,234,556,666,777]
    
    #Test Case 3
    #array of 1000 numbers
